{% set name = "tkutil" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tkutil-{{ version }}.tar.gz
  sha256: e928c850adb12a6446361131dc3f6816c39515061f34f4fdf2e4abe0b13abe2f

build:
  entry_points:
    - tkutil = tkutil.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - shared

test:
  imports:
    - tkutil
  commands:
    - pip check
    - tkutil --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/tkutil
  summary: Tkinter utilities for Pyrustic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
